[project]
name = "liuyao"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kivy[base]>=2.3.1",
    "kivymd>=1.2.0",
    "tyme4py>=1.4.4",
]
