name: Release Android APK

# 触发规则：仅Tag推送
on:
  push:
    tags: ['v*']  # 所有Tag（如v1.0.0）
  workflow_dispatch: # 手动触发发布（可选）

env:
  APP_ANDROID_ARCH: armeabi-v8a

jobs:
  build-and-release:
    name: Build & Release APK
    runs-on: ubuntu-latest
    environment: sign
    permissions:
      contents: write  # 发布Release需要的权限
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: n8marti/buildozer-action@fix-user-doesnt-exist
        id: buildozer
        with:
          command: buildozer android release
          workdir: .
          buildozer_version: stable


      # 2. 签名 APK（生成 *-unsigned-signed.apk，保留原始文件名）
      - name: Sign APK (Release)
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: bin
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          # keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      # 3. 创建空的 GitHub Release（先创建，才能上传产物）
      - name: Create Empty Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # 自动获取Tag（如v1.0.0）
          release_name: Release ${{ github.ref_name }}  # Release标题
          draft: false  # 是否为草稿（false=直接发布）
          prerelease: false  # 是否为预发布
          body: "Automatically released signed APK for ${{ github.ref_name }}" # 自定义描述


      - name: Upload APK (arm64-v8a)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{steps.sign_apk.outputs.signedReleaseFile}}
          asset_name: LiuYao-${{ github.ref_name }}-arm64-v8a.apk
          asset_content_type: application/zip

